# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/msa.azzazy.AUC/piplined/piplined.cache/wt [current_project]
set_property parent.project_path C:/Users/msa.azzazy.AUC/piplined/piplined.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/msa.azzazy.AUC/piplined/piplined.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/Full_Adder.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/Mux2_1.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/FlipFlop.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/RippleAdder.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/AdderSub.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/RegWLoad.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/Decoder5_32.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/RegFile.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/ControlUnit.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/InstMem.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/ShiftLeft1.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/ALU.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/ALUControl.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/DataMem.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/ImmGen.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/RISCV.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/SSDDriver.v
  C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/sources_1/imports/Lab7Src/RISCV_Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/constrs_1/imports/Lab7Src/PackagePins.xdc
set_property used_in_implementation false [get_files C:/Users/msa.azzazy.AUC/piplined/piplined.srcs/constrs_1/imports/Lab7Src/PackagePins.xdc]


synth_design -top RISCV_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef RISCV_Top.dcp

catch { report_utilization -file RISCV_Top_utilization_synth.rpt -pb RISCV_Top_utilization_synth.pb }
